// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package user

import (
	"time"

	"github.com/google/uuid"
)

type Category struct {
	ID        uuid.UUID     `db:"id"`
	Name      string        `db:"name"`
	Type      int32         `db:"type"`
	Color     string        `db:"color"`
	UserID    uuid.UUID     `db:"user_id"`
	Version   int32         `db:"version"`
	Deleted   bool          `db:"deleted"`
	CreatedAt time.Time     `db:"created_at"`
	CreatedBy uuid.NullUUID `db:"created_by"`
	UpdatedAt *time.Time    `db:"updated_at"`
	UpdatedBy uuid.NullUUID `db:"updated_by"`
}

type Usuario struct {
	ID           uuid.UUID     `db:"id"`
	Nome         string        `db:"nome"`
	Telefone     string        `db:"telefone"`
	Email        string        `db:"email"`
	IsAtivo      bool          `db:"is_ativo"`
	PasswordHash []byte        `db:"password_hash"`
	Version      int32         `db:"version"`
	Deleted      bool          `db:"deleted"`
	CreatedAt    time.Time     `db:"created_at"`
	CreatedBy    uuid.NullUUID `db:"created_by"`
	UpdatedAt    *time.Time    `db:"updated_at"`
	UpdatedBy    uuid.NullUUID `db:"updated_by"`
}
