// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package user

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteUser = `-- name: DeleteUser :exec
UPDATE usuarios SET deleted = true, version = version + 1, updated_at = now()
WHERE id = $1 AND deleted = false
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, nome, telefone, email, is_ativo, password_hash, version, deleted, created_at, created_by, updated_at, updated_by
FROM usuarios
WHERE email = $1 AND deleted = false
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (Usuario, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Telefone,
		&i.Email,
		&i.IsAtivo,
		&i.PasswordHash,
		&i.Version,
		&i.Deleted,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one


SELECT id, nome, telefone, email, is_ativo, password_hash, version, deleted, created_at, created_by, updated_at, updated_by
FROM usuarios
WHERE id = $1 AND deleted = false
`

// sql/queries.sql
// ===================== USUÁRIOS =====================
func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (Usuario, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Telefone,
		&i.Email,
		&i.IsAtivo,
		&i.PasswordHash,
		&i.Version,
		&i.Deleted,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO usuarios (nome, telefone, email, is_ativo, password_hash, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, version, created_at
`

type InsertUserParams struct {
	Nome         string        `db:"nome"`
	Telefone     string        `db:"telefone"`
	Email        string        `db:"email"`
	IsAtivo      bool          `db:"is_ativo"`
	PasswordHash []byte        `db:"password_hash"`
	CreatedBy    uuid.NullUUID `db:"created_by"`
}

type InsertUserRow struct {
	ID        uuid.UUID `db:"id"`
	Version   int32     `db:"version"`
	CreatedAt time.Time `db:"created_at"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Nome,
		arg.Telefone,
		arg.Email,
		arg.IsAtivo,
		arg.PasswordHash,
		arg.CreatedBy,
	)
	var i InsertUserRow
	err := row.Scan(&i.ID, &i.Version, &i.CreatedAt)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE usuarios
SET nome = $2, telefone = $3, email = $4, is_ativo = $5, password_hash = $6,
    version = version + 1, updated_at = now(), updated_by = $7
WHERE id = $1 AND deleted = false
RETURNING id, version, updated_at
`

type UpdateUserParams struct {
	ID           uuid.UUID     `db:"id"`
	Nome         string        `db:"nome"`
	Telefone     string        `db:"telefone"`
	Email        string        `db:"email"`
	IsAtivo      bool          `db:"is_ativo"`
	PasswordHash []byte        `db:"password_hash"`
	UpdatedBy    uuid.NullUUID `db:"updated_by"`
}

type UpdateUserRow struct {
	ID        uuid.UUID  `db:"id"`
	Version   int32      `db:"version"`
	UpdatedAt *time.Time `db:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Nome,
		arg.Telefone,
		arg.Email,
		arg.IsAtivo,
		arg.PasswordHash,
		arg.UpdatedBy,
	)
	var i UpdateUserRow
	err := row.Scan(&i.ID, &i.Version, &i.UpdatedAt)
	return i, err
}
