// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package categories

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCategory = `-- name: DeleteCategory :exec
UPDATE categories SET deleted = true, version = version + 1, updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted = false
`

type DeleteCategoryParams struct {
	ID     uuid.UUID `db:"id"`
	UserID uuid.UUID `db:"user_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.UserID)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one


SELECT
    c.id, c.name, c.type, c.color, c.user_id,
    c.version, c.created_at, c.updated_at,
    u.id                  AS usuario_id,
    u.nome                AS usuario_nome,
    u.telefone            AS usuario_telefone,
    u.email               AS usuario_email,
    u.is_ativo            AS usuario_is_ativo,
    u.password_hash       AS usuario_password_hash,
    u.version             AS usuario_version,
    u.deleted             AS usuario_deleted,
    u.created_at          AS usuario_created_at,
    u.created_by          AS usuario_created_by,
    u.updated_at          AS usuario_updated_at,
    u.updated_by          AS usuario_updated_by
FROM categories c
LEFT JOIN usuarios u ON c.user_id = u.id AND u.deleted = false
WHERE c.id = $1 AND c.deleted = false
`

type GetCategoryByIDRow struct {
	ID                  uuid.UUID     `db:"id"`
	Name                string        `db:"name"`
	Type                int32         `db:"type"`
	Color               string        `db:"color"`
	UserID              uuid.UUID     `db:"user_id"`
	Version             int32         `db:"version"`
	CreatedAt           time.Time     `db:"created_at"`
	UpdatedAt           *time.Time    `db:"updated_at"`
	UsuarioID           uuid.NullUUID `db:"usuario_id"`
	UsuarioNome         pgtype.Text   `db:"usuario_nome"`
	UsuarioTelefone     pgtype.Text   `db:"usuario_telefone"`
	UsuarioEmail        pgtype.Text   `db:"usuario_email"`
	UsuarioIsAtivo      pgtype.Bool   `db:"usuario_is_ativo"`
	UsuarioPasswordHash []byte        `db:"usuario_password_hash"`
	UsuarioVersion      pgtype.Int4   `db:"usuario_version"`
	UsuarioDeleted      pgtype.Bool   `db:"usuario_deleted"`
	UsuarioCreatedAt    *time.Time    `db:"usuario_created_at"`
	UsuarioCreatedBy    uuid.NullUUID `db:"usuario_created_by"`
	UsuarioUpdatedAt    *time.Time    `db:"usuario_updated_at"`
	UsuarioUpdatedBy    uuid.NullUUID `db:"usuario_updated_by"`
}

// sql/queries.sql
// ===================== CATEGORIES =====================
func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (GetCategoryByIDRow, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i GetCategoryByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Color,
		&i.UserID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsuarioID,
		&i.UsuarioNome,
		&i.UsuarioTelefone,
		&i.UsuarioEmail,
		&i.UsuarioIsAtivo,
		&i.UsuarioPasswordHash,
		&i.UsuarioVersion,
		&i.UsuarioDeleted,
		&i.UsuarioCreatedAt,
		&i.UsuarioCreatedBy,
		&i.UsuarioUpdatedAt,
		&i.UsuarioUpdatedBy,
	)
	return i, err
}

const insertCategory = `-- name: InsertCategory :one
INSERT INTO categories (name, type, color, user_id, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, version, created_at
`

type InsertCategoryParams struct {
	Name      string        `db:"name"`
	Type      int32         `db:"type"`
	Color     string        `db:"color"`
	UserID    uuid.UUID     `db:"user_id"`
	CreatedBy uuid.NullUUID `db:"created_by"`
}

type InsertCategoryRow struct {
	ID        uuid.UUID `db:"id"`
	Version   int32     `db:"version"`
	CreatedAt time.Time `db:"created_at"`
}

func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (InsertCategoryRow, error) {
	row := q.db.QueryRow(ctx, insertCategory,
		arg.Name,
		arg.Type,
		arg.Color,
		arg.UserID,
		arg.CreatedBy,
	)
	var i InsertCategoryRow
	err := row.Scan(&i.ID, &i.Version, &i.CreatedAt)
	return i, err
}

const listCategoriesByUser = `-- name: ListCategoriesByUser :many
SELECT
    c.id, c.name, c.type, c.color, c.user_id,
    c.version, c.created_at, c.updated_at,
    u.id                  AS usuario_id,
    u.nome                AS usuario_nome,
    u.telefone            AS usuario_telefone,
    u.email               AS usuario_email,
    u.is_ativo            AS usuario_is_ativo,
    u.password_hash       AS usuario_password_hash,
    u.version             AS usuario_version,
    u.deleted             AS usuario_deleted,
    u.created_at          AS usuario_created_at,
    u.created_by          AS usuario_created_by,
    u.updated_at          AS usuario_updated_at,
    u.updated_by          AS usuario_updated_by
FROM categories c
LEFT JOIN usuarios u ON c.user_id = u.id AND u.deleted = false
WHERE c.user_id = $1 AND c.deleted = false
ORDER BY c.name
`

type ListCategoriesByUserRow struct {
	ID                  uuid.UUID     `db:"id"`
	Name                string        `db:"name"`
	Type                int32         `db:"type"`
	Color               string        `db:"color"`
	UserID              uuid.UUID     `db:"user_id"`
	Version             int32         `db:"version"`
	CreatedAt           time.Time     `db:"created_at"`
	UpdatedAt           *time.Time    `db:"updated_at"`
	UsuarioID           uuid.NullUUID `db:"usuario_id"`
	UsuarioNome         pgtype.Text   `db:"usuario_nome"`
	UsuarioTelefone     pgtype.Text   `db:"usuario_telefone"`
	UsuarioEmail        pgtype.Text   `db:"usuario_email"`
	UsuarioIsAtivo      pgtype.Bool   `db:"usuario_is_ativo"`
	UsuarioPasswordHash []byte        `db:"usuario_password_hash"`
	UsuarioVersion      pgtype.Int4   `db:"usuario_version"`
	UsuarioDeleted      pgtype.Bool   `db:"usuario_deleted"`
	UsuarioCreatedAt    *time.Time    `db:"usuario_created_at"`
	UsuarioCreatedBy    uuid.NullUUID `db:"usuario_created_by"`
	UsuarioUpdatedAt    *time.Time    `db:"usuario_updated_at"`
	UsuarioUpdatedBy    uuid.NullUUID `db:"usuario_updated_by"`
}

func (q *Queries) ListCategoriesByUser(ctx context.Context, userID uuid.UUID) ([]ListCategoriesByUserRow, error) {
	rows, err := q.db.Query(ctx, listCategoriesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesByUserRow
	for rows.Next() {
		var i ListCategoriesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Color,
			&i.UserID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UsuarioID,
			&i.UsuarioNome,
			&i.UsuarioTelefone,
			&i.UsuarioEmail,
			&i.UsuarioIsAtivo,
			&i.UsuarioPasswordHash,
			&i.UsuarioVersion,
			&i.UsuarioDeleted,
			&i.UsuarioCreatedAt,
			&i.UsuarioCreatedBy,
			&i.UsuarioUpdatedAt,
			&i.UsuarioUpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $2, type = $3, color = $4, version = version + 1, updated_at = now(), updated_by = $5
WHERE id = $1 AND user_id = $6 AND deleted = false
RETURNING id, version, updated_at
`

type UpdateCategoryParams struct {
	ID        uuid.UUID     `db:"id"`
	Name      string        `db:"name"`
	Type      int32         `db:"type"`
	Color     string        `db:"color"`
	UpdatedBy uuid.NullUUID `db:"updated_by"`
	UserID    uuid.UUID     `db:"user_id"`
}

type UpdateCategoryRow struct {
	ID        uuid.UUID  `db:"id"`
	Version   int32      `db:"version"`
	UpdatedAt *time.Time `db:"updated_at"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (UpdateCategoryRow, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Color,
		arg.UpdatedBy,
		arg.UserID,
	)
	var i UpdateCategoryRow
	err := row.Scan(&i.ID, &i.Version, &i.UpdatedAt)
	return i, err
}
